services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: powerdns
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=sinlessgames-frontend"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - pdns_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  pdns_authoritative:
    image: powerdns/pdns-auth-master:latest
    container_name: pdns_authoritative
    environment:
      DEBUG: true
      BACKEND: gmysql
      PDNS_master: yes
      PDNS_api: yes
      PDNS_api_key: ${PDNS_API_KEY}
      PDNS_webserver: yes
      PDNS_webserver_address: 0.0.0.0
      PDNS_GMYSQL_HOST: mysql
      PDNS_GMYSQL_PORT: 3306
      PDNS_GMYSQL_USER: root
      PDNS_GMYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PDNS_GMYSQL_DBNAME: powerdns
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=sinlessgames-frontend"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - pdns_network
    ports:
      - "192.168.1.3:53:53/tcp"
      - "192.168.1.3:53:53/udp"
      - "8081:8081"   # API and webserver port
    healthcheck:
      test: ["CMD", "pdns_control", "rping"]
      interval: 30s
      timeout: 10s
      retries: 3

  pdns_admin:
    image: pschiffe/pdns-admin:latest
    container_name: pdns_admin
    environment:
      DBBACKEND: mysql
      PDNS_ADMIN_SQLA_DB_TYPE: mysql
      PDNS_ADMIN_SQLA_DB_HOST: mysql
      PDNS_ADMIN_SQLA_DB_PORT: 3306
      PDNS_ADMIN_SQLA_DB_USER: root
      PDNS_ADMIN_SQLA_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PDNS_ADMIN_SQLA_DB_NAME: powerdns
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=sinlessgames-frontend"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    depends_on:
      pdns_authoritative:
        condition: service_healthy
    ports:
      - 9494:9494
    networks:
      - pdns_network
    volumes:
      - ./.data/pdns-admin:/var/lib/powerdns-admin
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://127.0.0.1:9494/ || exit 1"]
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: pdns_nginx
    depends_on:
      pdns_admin:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.3:3100/loki/api/v1/push"
        loki-external-labels: "container_name=sinlessgames-frontend"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    networks:
      - pdns_network
    ports:
      - "8082:80"   # Expose Nginx on port 8082 externally (adjust as needed)
    volumes:
      - ./configs/nginx-pdns-admin.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  pdns_network:
    driver: bridge
